### ISSUE TITLE
Ability to export package name mapping between multiple package managers

### ISSUE THREAD

**Issue by anadon** [repology/repology-exports#4]
I'm looking to have a script ease my transition away from Ubuntu and towards Nix and Guix.  In order to make this easier, I would like the ability to get a mapping of a package name in `apt` to names in Nix and Guix.  Repology overall definitely has this mapping, I just don't see an immediate way to obtain this information without a ton of scraping and overhead.

**Comment by AMDmi3** [comment]
Try https://repology.org/experimental/distromap

**Comment by anadon** [comment]
No dice.
https://repology.org/api/experimental/distromap?fromrepo=ubuntu_23_10&torepo=gnuguix&expand=on&format=json
yields packages which are grouped in an incorrect order and from/to repo is
not clear.  These are also repo based and not distro based, so I would need
a way to aggregate repos to represent distro and ideally distro shorthands
to provide default aggregations of repos.  I've only gotten to look at the
JSON result because I'm traveling.

I'd also find the following formats more usable:
JSON:
```
{
"Global name": {
"Distro 1": {
"Name": "distro specific name",
"Version": "version string",
<Other info>,
},
...
}
```

Plaintext:
```
<Dist 1 name> ...  <Dist N name>
<Package name for dist 1> ... <Package name for dist N>
```

Does that make sense?  The tabular data is especially consumable in scripts.

**Comment by AMDmi3** [comment]
I don't have any other out of box solutions. You can get a database dump from https://dumps.repology.org/ and bake any dataset you like out of it.

**Comment by anadon** [comment]
That meets my needs.
